Repository LordNani/tak-scheduler, pull requests merged in 2021-11, with the labels that each got.

#23 Feature/swagger docs
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/tak-scheduler.iml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/controller/TagController.java
  backend/src/main/java/com/simpletak/takscheduler/dto/tag/TagRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/repository/tag/TagRepository.java
  backend/src/main/java/com/simpletak/takscheduler/service/tag/TagService.java
  backend/src/main/resources/application-dev.properties
Labels: type:features, type:documentation, type:config

#24 Fixed usercontroller methods
  backend/src/main/java/com/simpletak/takscheduler/controller/UserController.java
  backend/src/main/java/com/simpletak/takscheduler/dto/user/EditUserRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/exception/user/SuchUserAlreadyExistsException.java
  backend/src/main/java/com/simpletak/takscheduler/service/user/UserService.java
Labels: type:features

#25 docs, postman json
  backend/src/main/resources/postman.json
  backend/src/main/resources/swagger.json
Labels: type:documentation

#26 WEEK 11
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/tak-scheduler.iml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/config/RestResponseExceptionHandler.java
  backend/src/main/java/com/simpletak/takscheduler/controller/TagController.java
  backend/src/main/java/com/simpletak/takscheduler/controller/UserController.java
  backend/src/main/java/com/simpletak/takscheduler/controller/event/EventController.java
  backend/src/main/java/com/simpletak/takscheduler/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/dto/event/EventDTO.java
  backend/src/main/java/com/simpletak/takscheduler/dto/eventGroup/EventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/dto/tag/TagRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/dto/user/EditUserRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/exception/event/EventNotFoundException.java
  backend/src/main/java/com/simpletak/takscheduler/exception/user/SuchUserAlreadyExistsException.java
  backend/src/main/java/com/simpletak/takscheduler/model/event/EventEntity.java
  backend/src/main/java/com/simpletak/takscheduler/repository/tag/TagRepository.java
  backend/src/main/java/com/simpletak/takscheduler/service/event/EventService.java
  backend/src/main/java/com/simpletak/takscheduler/service/eventgroup/EventGroupService.java
  backend/src/main/java/com/simpletak/takscheduler/service/tag/TagService.java
  backend/src/main/java/com/simpletak/takscheduler/service/user/UserService.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/postman.json
  backend/src/main/resources/swagger.json
Labels: type:features, type:fix, type:documentation, type:config

#27 Fix/entities
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/tak-scheduler.iml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/src/main/java/com/simpletak/takscheduler/controller/TagController.java
  backend/src/main/java/com/simpletak/takscheduler/exception/NotMatchingDataException.java
  backend/src/main/java/com/simpletak/takscheduler/model/event/EventEntity.java
  backend/src/main/java/com/simpletak/takscheduler/service/tag/TagService.java
Labels: type:features, type:fix

#29 Implemented "Authorization"
  backend/src/main/java/com/simpletak/takscheduler/TakschedulerApplicationDev.java
  backend/src/main/java/com/simpletak/takscheduler/config/SecurityConfiguration.java
  backend/src/main/java/com/simpletak/takscheduler/config/security/PasswordBean.java
  backend/src/main/java/com/simpletak/takscheduler/config/security/SecurityConfiguration.java
  backend/src/main/java/com/simpletak/takscheduler/config/security/jwt/JwtFilter.java
  backend/src/main/java/com/simpletak/takscheduler/config/security/jwt/JwtProvider.java
  backend/src/main/java/com/simpletak/takscheduler/config/security/jwt/JwtProviderImpl.java
  backend/src/main/java/com/simpletak/takscheduler/controller/tag/TagController.java
  backend/src/main/java/com/simpletak/takscheduler/controller/user/UserController.java
  backend/src/main/java/com/simpletak/takscheduler/controller/user/role/RoleController.java
  backend/src/main/java/com/simpletak/takscheduler/dto/event/EventMapper.java
  backend/src/main/java/com/simpletak/takscheduler/dto/user/role/RoleDTO.java
  backend/src/main/java/com/simpletak/takscheduler/dto/user/role/RoleMapper.java
  backend/src/main/java/com/simpletak/takscheduler/exception/WebException.java
  backend/src/main/java/com/simpletak/takscheduler/exception/user/role/RoleNotFoundException.java
  backend/src/main/java/com/simpletak/takscheduler/model/user/CustomUserDetails.java
  backend/src/main/java/com/simpletak/takscheduler/model/user/UserEntity.java
  backend/src/main/java/com/simpletak/takscheduler/model/user/role/RoleEntity.java
  backend/src/main/java/com/simpletak/takscheduler/repository/user/UserRepository.java
  backend/src/main/java/com/simpletak/takscheduler/repository/user/role/RoleEntityRepository.java
  backend/src/main/java/com/simpletak/takscheduler/service/authentication/UserDetailsServiceImpl.java
  backend/src/main/java/com/simpletak/takscheduler/service/user/UserService.java
  backend/src/main/java/com/simpletak/takscheduler/service/user/role/RoleService.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-prod.properties
Labels: type:features, type:config

#31 Added automatic creation of roles (admin, user), admin user if they don't exist
  backend/src/main/java/com/simpletak/takscheduler/config/ApplicationListenerInitialize.java
  backend/src/main/java/com/simpletak/takscheduler/config/security/SecurityConfiguration.java
  backend/src/main/java/com/simpletak/takscheduler/dto/user/SignupUserRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/repository/user/UserRepository.java
  backend/src/main/java/com/simpletak/takscheduler/repository/user/role/RoleEntityRepository.java
  backend/src/main/java/com/simpletak/takscheduler/service/user/UserService.java
  backend/src/main/java/com/simpletak/takscheduler/service/user/role/RoleService.java
Labels: type:fix
