Repository LordNani/tak-scheduler, pull requests merged in 2021-12, with the labels that each got.

#33 Implemented "AOP for methods in service package"
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/api/TakschedulerApplicationDev.java
  backend/src/main/java/com/simpletak/takscheduler/api/TakschedulerApplicationProd.java
  backend/src/main/java/com/simpletak/takscheduler/api/aop/LogAspect.java
  backend/src/main/java/com/simpletak/takscheduler/api/aop/LogAspectExpressions.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/ApplicationListenerInitialize.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/jwt/JwtFilter.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/user/UserController.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/user/UserService.java
Labels: type:features

#34 Feature/person view
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/api/aop/LogAspect.java
  backend/src/main/java/com/simpletak/takscheduler/api/aop/LogAspectExpressions.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/CookieFilter.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/SecurityConfiguration.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/jwt/JwtFilter.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/jwt/JwtProvider.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/jwt/JwtProviderImpl.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/user/UserController.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/tagEventGroup/TagEventGroupEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/repository/tagEventGroup/TagEventGroupRepository.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/eventgroup/EventGroupService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/tag/TagService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/user/UserService.java
  backend/src/main/java/com/simpletak/takscheduler/api/view/AuthController.java
  backend/src/main/java/com/simpletak/takscheduler/api/view/MainController.java
  backend/src/main/java/com/simpletak/takscheduler/view/controller/PersonController.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/static/css_js/css/auth.css
  backend/src/main/resources/static/css_js/css/fragments/header.css
  backend/src/main/resources/static/css_js/css/main.css
  backend/src/main/resources/static/css_js/css/profile.css
  backend/src/main/resources/static/css_js/js/auth.js
  backend/src/main/resources/templates/auth.html
  backend/src/main/resources/templates/event-groups.html
  backend/src/main/resources/templates/fragments/header.html
  backend/src/main/resources/templates/index.html
  backend/src/main/resources/templates/profile.html
  backend/src/main/resources/templates/tag.html
Labels: type:features

#35 Feature/event group to user
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/api/config/ApplicationListenerInitialize.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/security/SecurityConfiguration.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/subscription/SubscriptionController.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/NewEventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/subscription/SubscriptionDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/subscription/SubscriptionMapper.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/eventGroup/EventGroupEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/subscription/SubscriptionEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/repository/eventGroup/EventGroupRepositoryPagingAndSorting.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/eventgroup/EventGroupService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/subscription/SubscriptionService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/subscription/SubscriptionServiceImpl.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/user/UserService.java
Labels: type:features

#36 Implemented unsubscribe function.
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/subscription/SubscriptionController.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/subscription/SubscriptionMapper.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/subscription/SubscriptionRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/subscription/SubscriptionResponseDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/exception/subscription/SubscriptionAlreadyExistsException.java
  backend/src/main/java/com/simpletak/takscheduler/api/exception/subscription/SubscriptionNotFoundException.java
  backend/src/main/java/com/simpletak/takscheduler/api/repository/subscription/SubscriptionRepository.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/subscription/SubscriptionService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/subscription/SubscriptionServiceImpl.java
  backend/src/main/resources/postman.json
Labels: type:features

#37 Feature/scheduling
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/api/TakschedulerApplicationDev.java
  backend/src/main/java/com/simpletak/takscheduler/api/TakschedulerApplicationProd.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/ApplicationListenerInitialize.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/cache/CachingConfig.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/scheduling/EventSchedulingConfig.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/event/EventController.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/api/exception/InvalidCronExpressionException.java
  backend/src/main/java/com/simpletak/takscheduler/api/init/InitEventScheduling.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/event/EventEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/event/scheduling/EventSchedulingByCronDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/event/scheduling/EventSchedulingByDateDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/repository/event/EventRepository.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/EventService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/scheduling/EventRunnableTask.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/eventgroup/EventGroupService.java
Labels: type:features

#38 Feature/dto isowned
  backend/src/main/java/com/simpletak/takscheduler/api/config/ApplicationListenerInitialize.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/EventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/EventGroupMapper.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/NewEventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/exception/user/UserIsNotPermittedException.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/EventService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/eventgroup/EventGroupService.java
Labels: type:features

#39 Frontend
  backend/src/main/java/com/simpletak/takscheduler/api/config/ApplicationListenerInitialize.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/event/EventController.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupController.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/event/EventDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/event/EventMapper.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/event/NewEventDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/EventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/EventGroupMapper.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/eventGroup/NewEventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/exception/event/IncorrectYearOrTimeRangeException.java
  backend/src/main/java/com/simpletak/takscheduler/api/init/InitEventScheduling.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/event/EventEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/repository/event/EventRepository.java
  backend/src/main/java/com/simpletak/takscheduler/api/repository/subscription/SubscriptionRepository.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/EventService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/scheduling/EventRunnableTask.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/eventgroup/EventGroupService.java
  backend/src/main/java/com/simpletak/takscheduler/api/view/MainController.java
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/static/css_js/css/calendar.css
  backend/src/main/resources/static/css_js/css/create-event-group.css
  backend/src/main/resources/static/css_js/css/event-groups.css
  backend/src/main/resources/static/css_js/css/fragments/header.css
  backend/src/main/resources/static/css_js/css/index.css
  backend/src/main/resources/static/css_js/css/profile.css
  backend/src/main/resources/static/css_js/js/calendar.js
  backend/src/main/resources/templates/create-event-group.html
  backend/src/main/resources/templates/event-groups.html
  backend/src/main/resources/templates/fragments/event-group-list.html
  backend/src/main/resources/templates/fragments/header.html
  backend/src/main/resources/templates/index.html
  backend/src/main/resources/templates/my-event-groups.html
Labels: type:features

#40 Implemented TagEventGroup
  backend/src/main/java/com/simpletak/takscheduler/api/config/cache/CachingConfig.java
  backend/src/main/java/com/simpletak/takscheduler/api/config/cache/SimpleCacheManager.java
  backend/src/main/java/com/simpletak/takscheduler/api/controller/eventgroup/EventGroupToTagController.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/tagEventGroup/TagEventGroupDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/dto/tagEventGroup/TagEventGroupMapper.java
  backend/src/main/java/com/simpletak/takscheduler/api/exception/user/UserIsNotAuthorizedException.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/eventGroup/EventGroupEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/tag/TagEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/tagEventGroup/TagEventGroupEntity.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/EventService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/eventgroup/EventGroupService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/tag/TagService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/tageventgroup/TagEventGroupService.java
  backend/src/main/java/com/simpletak/takscheduler/api/service/tageventgroup/TagEventGroupServiceImpl.java
Labels: type:features

#42 Added logout, fixed bug with calendar
  backend/src/main/java/com/simpletak/takscheduler/api/service/event/EventService.java
  backend/src/main/resources/static/css_js/css/fragments/header.css
  backend/src/main/resources/templates/fragments/header.html
  backend/src/main/resources/templates/index.html
Labels: type:fix

#41 quick fix typo
  backend/src/main/resources/templates/create-event-group.html
  backend/src/main/resources/templates/profile.html
Labels: type:fix

#43 Tag creation
  backend/pom.xml
  backend/src/main/java/com/simpletak/takscheduler/api/dto/tag/TagRequestDTO.java
  backend/src/main/java/com/simpletak/takscheduler/api/model/tag/TagEntity.java
  backend/src/main/resources/static/css_js/css/tag.css
  backend/src/main/resources/templates/auth.html
  backend/src/main/resources/templates/create-event-group.html
  backend/src/main/resources/templates/event-groups.html
  backend/src/main/resources/templates/fragments/event-group-list.html
  backend/src/main/resources/templates/fragments/header.html
  backend/src/main/resources/templates/index.html
  backend/src/main/resources/templates/my-event-groups.html
  backend/src/main/resources/templates/profile.html
  backend/src/main/resources/templates/tag.html
Labels: type:features, type:fix

#44 Update tag.css
  backend/src/main/resources/static/css_js/css/tag.css
Labels: type:features
